package org.drools.servlet
import org.drools.servlet.SamManager;
import org.drools.servlet.DecisionParameter;

global java.util.Map globals

rule "SamManagerDecision"
    when
    	DecisionParameter($emisor : emisor, $montoRequested : monto)
    	$samSelected : SamManager(getMontoEmisor($emisor) != null, getMontoEmisor($emisor) >= $montoRequested, $operations : operations)
    	not SamManager( getMontoEmisor($emisor) > $samSelected.getMontoEmisor($emisor) )
    then
        globals.put("Result", $samSelected);
        System.out.println("ENTRA REGLA PRINCIPAL"+ $samSelected);
end


rule "SamManagerDecision4"
    then
        System.out.println("ENTRA SIEMPRE");
end